package com.farmlink.backend.enums;
public enum NotificationType {
    RENTAL_REQUEST_RECEIVED, RENTAL_REQUEST_ACCEPTED, RENTAL_REQUEST_REJECTED,
    HIRE_REQUEST_RECEIVED, HIRE_REQUEST_ACCEPTED, HIRE_REQUEST_REJECTED,
    JOB_APPLICATION_RECEIVED, JOB_APPLICATION_ACCEPTED, JOB_APPLICATION_REJECTED
}