apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmlink-frontend-deployment
spec:
  replicas: {{ .Values.frontend.replicaCount}}
  selector:
    matchLabels:
      app: farmlink-frontend
  template:
    metadata:
      labels:
        app: farmlink-frontend
    spec:
      containers:
      - name: farmlink-frontend
        image: {{ .Values.frontend.image.repository}}:{{ .Values.frontend.image.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.frontend.port}}