apiVersion: v1
kind: Service
metadata:
  name: farmlist-frontend-service
spec:
  selector:
    app: farmlist-frontend
  ports:
  - port: {{ .Values.frontend.port}}
    targetPort: {{ .Values.frontend.port}}
    nodePort: {{ .Values.frontend.nodePort}}
  type: NodePort