apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmlist-frontend-deployment
spec:
  replicas: {{ .Values.frontend.replicaCount}}
  selector:
    matchLabels:
      app: farmlist-frontend
  template:
    metadata:
      labels:
        app: farmlist-frontend
    spec:
      containers:
      - name: farmlist-frontend
        image: {{ .Values.frontend.image.repository}}:{{ .Values.frontend.image.tag}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.frontend.port}}