apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: farmlink-minio-statefulset
spec:
  replicas: 1 
  serviceName: farmlink-minio-service 
  selector:
    matchLabels:
      app: farmlink-minio
  template:
    metadata:
      labels:
        app: farmlink-minio
    spec:
      containers:
      - name: farmlink-minio
        image: {{ .Values.minio.image.repository}}:{{ .Values.minio.image.tag}}
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - minio server /data --console-address :9001
        ports:
        - containerPort: {{ .Values.minio.port }}
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: farmlink-secret
                key: MINIO_ROOT_USER

          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: farmlink-secret
                key: MINIO_ROOT_PASSWORD

          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: farmlink-secret
                key: MINIO_ACCESS_KEY

          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: farmlink-secret
                key: MINIO_SECRET_KEY

        volumeMounts:
          - name: minio-data
            mountPath: /data
  
  volumeClaimTemplates:    # ← this replaces volumes section
  - metadata:
      name: minio-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.minio.storage }}