apiVersion: v1
kind: Service
metadata:
  name: farmlist-minio-service
spec:
  selector:
    app: farmlist-minio
  ports:
  - name: api
    port: {{ .Values.minio.port }}
    targetPort: {{ .Values.minio.port }}
  - name: console
    port: {{ .Values.minio.consolePort }}
    targetPort: {{ .Values.minio.consolePort }}
  type: ClusterIP