apiVersion: v1
kind: Service
metadata:
  name: farmlink-postgres-service
spec:
  clusterIP: None    # ← headless! allows StatefulSet DNS
  selector:
    app: farmlink-postgres
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}