apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: farmlist-postgres-statefulset
spec:
  replicas: 1 
  serviceName: farmlist-postgres-service 
  selector:
    matchLabels:
      app: farmlist-postgres
  template:
    metadata:
      labels:
        app: farmlist-postgres
    spec:
      containers:
      - name: farmlist-postgres
        image: {{ .Values.postgres.image.repository}}:{{ .Values.postgres.image.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.postgres.port }}
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: farmlist-configmap
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: farmlist-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: farmlist-secret
                key: POSTGRES_PASSWORD
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:    # ← this replaces volumes section
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.postgres.storage }}