apiVersion: v1
kind: Secret
metadata: 
  name: farmlink-secret
type: Opaque
data:
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | b64enc}}
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | b64enc}}
  JWT_SECRET: {{ .Values.app.jwtSecret | b64enc}}
  POSTGRES_USER: {{ .Values.postgres.username | b64enc}}
  POSTGRES_PASSWORD: {{ .Values.postgres.password |b64enc}}