apiVersion: v1
kind: Secret
metadata: 
  name: farmlist-secret
type: Opaque
data:
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | b64enc}}
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | b64enc}}
  JWT_SECRET: {{ .Values.app.jwtSecret | b64enc}}
  POSTGRES_USER: {{ .Values.postgres.username | b64enc}}
  POSTGRES_PASSWORD: {{ .Values.postgres.password |b64enc}}
  MINIO_ACCESS_KEY: {{ .Values.minio.rootUser | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.minio.rootPassword | b64enc }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgres.username | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.password | b64enc }}